### PR TITLE
Change structure of mets.md

### LINKED ISSUE #142: allow global fptrs in structMap
Currently, we only specify how to describe the hierarchy of pages (represented by a set of files under `mets:structMap/mets:div/mets:div`) and their order. But nothing so far on logical structure **across pages** (table of contents, via `mets:structMap TYPE="LOGICAL"` and `mets:smLink`) or other **global** representations. For the latter METS offers adding a set of files (`mets:fptr`s) directly under the top `mets:structMap/mets:div` – this would allow pointing to other file formats representing the complete document on some level, e.g.:

- multi-page TIFF or PDF input files
- multi-page PDF output files (with text overlay from OCR results)
- [COCO format](http://cocodataset.org/#format-data) layout annotations
- TEI output representation
- OCR/OLR evaluation reports accumulated for all pages
- alternative, custom file formats for logical structure
- ...

These could each reside in dedicated `mets:fileGrp`s, so (with a little work) even our notion of _workspace processor_ (reading from input file groups and writing to output file groups) could be generalized to allow encapsulating such converters within normal OCR-D CLIs.

For example, schematically, we could have:

```XML
<mets:fileGrp USE="OCR-D-IMG">
  <mets:file MIMETYPE="image/tiff" ID="TIFF-input">
    <mets:FLocat .../>
  </mets:file>
  <mets:file MIMETYPE="image/tiff" ID="TIFF-split_0001">
    <mets:FLocat .../>
  </mets:file>
  <mets:file MIMETYPE="image/tiff" ID="TIFF-split_0002">
    <mets:FLocat .../>
  </mets:file>
  ...
</mets:fileGrp>
<mets:fileGrp USE="OCR-D-TEI">
  <mets:file MIMETYPE="application/tei+xml" ID="TEI-output">
    <mets:FLocat .../>
  </mets:file>
</mets:fileGrp>
<mets:fileGrp USE="OCR-D-PDF">
  <mets:file MIMETYPE="application/pdf" ID="PDF-output">
    <mets:FLocat .../>
  </mets:file>
</mets:fileGrp>
...
<mets:structMap TYPE="PHYSICAL">
  <mets:div ID="physroot" TYPE="physSequence">
    <mets:div ID=... ORDER=... TYPE="page">
      <mets:fptr FILEID="TIFF-split_0001"/>
      <mets:fptr FILEID="OCR-D-SEG-PAGE_0001"/>
      <mets:fptr .../>
    </mets:div>
    ...
    <mets:fptr FILEID="TIFF-input"/>
    <mets:fptr FILEID="TEI-output"/>
    <mets:fptr FILEID="PDF-output"/>
  </mets:div>
</mets:structMap>
```

Related: #40. (The issue of conventions for logical structure has also been touched by #80 and OCR-D/core#304 before.)

### PR DESCRIPTION
**Pull request by tboenig**
<del>add structMap (fix #142 ).</del><ins>see #154 for that</ins>

Changes the document structure

### CODE REVIEW

**Comment by cneud** [comment]
This is already [published](https://ocr-d.de/en/spec/mets) - and probably has been for a while - so I assume we can close? @tboenig

**Comment by bertsky** [comment]
> This is already [published](https://ocr-d.de/en/spec/mets) - and probably has been for a while - so I assume we can close?

Huh? This PR is neither on the website nor in master.

*But* (apart from the required update/resolution) I don't think we want that:
- why should we downgrade all level-2 headings to level 3 (leaving nothing in between)?
- shouldn't moving the image section (if at all necessary) wait until #154 gets merged?

@tboenig please explain your rationale! (Also, mind that #154 [still needs](https://github.com/OCR-D/spec/pull/154#discussion_r474795780) to be worked upon.

(If my judgement is correct, than this should be closed, and once #154 is done, a new PR can move sections around.)

**Comment by cneud** [comment]
sorry @bertsky I was trying to go through what appeared like staled issues but apparently I've only scratched the surcface of the iceberg. I'll see what I can do to help with https://github.com/OCR-D/spec/pull/154 then.

**Comment by cneud** [comment]
> (If my judgement is correct, than this should be closed, and once #154 is done, a new PR can move sections around.)

Having looked at #154, I agree. Let's close this and complete #154, resulting changes should be implemented either there or in a new PR.

**Comment by EEngl52** [comment]
@tboenig can we close this PR and move forward with https://github.com/OCR-D/spec/pull/154 ?

**Comment by kba** [comment]
Superseded by https://github.com/OCR-D/spec/pull/207

**Pull request closed without merging**
